=== DonOzOn/FPT-University-Excercise/practiceSchema/public_html/tygia.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="tygia">
        <xs:complexType>
            <xs:sequence>
                <xs:element name ="tygias" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <!-- validate kihieu-->
                        <xs:sequence>
                            <xs:element name="kihieu">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="AUD"/>
                                        <xs:enumeration value="CAD"/>
                                        <xs:enumeration value="CHF"/>
                                        <xs:enumeration value="DKK"/>
                                        <xs:enumeration value="EUR"/>
                                        <xs:enumeration value="GBP"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <!-- validate ten ngoai te-->
                            <xs:element name="tenngoaite">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="AUST.DOLLAR"/>
                                        <xs:enumeration value="CANADIAN DOLLAR"/>
                                        <xs:enumeration value="SWISS FRANCE"/>
                                        <xs:enumeration value="DANISH KRONE"/>
                                        <xs:enumeration value="EURO"/>
                                        <xs:enumeration value="BRITISH POUND"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <!-- validate mua vao-->
                            <xs:element name="muavao">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[0-9]+(,[0-9]+)+"/>
                                    </xs:restriction>
                                </xs:simpleType>
                                
                            </xs:element>
                            <xs:element name="chuyenkhoan" type="xs:string"/>
                            <!-- validate ban ra-->
                            <xs:element name="banra">
                                         <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[0-9]+(,[0-9]+)+"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
            </xs:sequence>
            
        </xs:complexType>
        
    </xs:element>
</xs:schema>

=== DonOzOn/FPT-University-Excercise/practiceSchema/public_html/tygia.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<?xml-stylesheet type="text/css href="tygia.css"?>
<tygia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="tygia.xsd">
    <tygias>
        <kihieu>AUD</kihieu>
        <tenngoaite>AUST.DOLLAR</tenngoaite>
        <muavao>13,789</muavao>
        <chuyenkhoan>13,872</chuyenkhoan>
        <banra>14,103</banra>
    </tygias>
    <tygias>
        <kihieu>CAD</kihieu>
        <tenngoaite>CANADIAN DOLLAR</tenngoaite>
        <muavao>15,738</muavao>
        <chuyenkhoan>15,811.07</chuyenkhoan>
        <banra>16,112</banra>
    </tygias>
    <tygias>
        <kihieu>CHF</kihieu>
        <tenngoaite>SWISS FRANCE</tenngoaite>
        <muavao>16,323</muavao>
        <chuyenkhoan>16,438.91</chuyenkhoan>
        <banra>16,711</banra>
    </tygias>
    
</tygia>
