=== DonOzOn/FPT-University-Excercise/HTML5Application/public_html/Bookstore.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> 
    <element name="Bookstore">
        <complexType>
            <sequence>
                <element name="Book" minOccurs="0" maxOccurs="unbounded">
                    <complexType mixed="true">
                        <sequence>
                            <element name="Name" minOccurs="1" maxOccurs="1"></element>
                            <element name="Author" type="string" minOccurs="1" maxOccurs="1"/>
                            <element name="Price" minOccurs="1" maxOccurs="1"></element>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== DonOzOn/FPT-University-Excercise/HTML5Application/public_html/Bookstore.xml
<?xml version="1.0" encoding="UTF-8"?>
<Bookstore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="Bookstore.xsd">
    <Book>
        <Name>Lao Hac</Name>
        <Author>Nam Cao</Author>
        <Price>100</Price>
    </Book>
    <Book>
        <Name>Tat Den</Name>
        <Author>Ngo Tat To</Author>
        <Price>150</Price>
    </Book>
</Bookstore>
