=== DonOzOn/FPT-University-Excercise/DataBinding/xml-resources/jaxb/Bookstore/Bookstore.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> 
    <element name="Bookstore">
        <complexType>
            <sequence>
                <element name="Book" minOccurs="0" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="Name" type = "string"/>
                            <element name="Author" type="string" />
                            <element name="Price" type="float"/>
                        </sequence>
                        <attribute name = "id" type = "string" use = "required" />
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== DonOzOn/FPT-University-Excercise/DataBinding/build/classes/XML/Bookstore.xml
<?xml version="1.0" encoding="UTF-8"?>
<Bookstore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="Bookstore.xsd">
    <Book id="1">
        <Name>Lao Hac</Name>
        <Author>Nam Cao</Author>
        <Price>100</Price>
    </Book>
    <Book id="2">
        <Name>Tat Den</Name>
        <Author>Ngo Tat To</Author>
        <Price>150</Price>
    </Book>
</Bookstore>
