=== DonOzOn/FPT-University-Excercise/Assignment1/public_html/Problem1.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/Problem1.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE Books SYSTEM "Problem1.dtd">

    <Books>
    ...
    </Books>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Books (Book)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Book (#PCDATA|Author|ISBN|Price)*>
<!ATTLIST Book
    Category CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Author (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ISBN (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Price (#PCDATA)>

=== DonOzOn/FPT-University-Excercise/Assignment1/public_html/Problem1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE Books SYSTEM "Problem1.dtd">
<Books>		
	<Book Category="novel">
            Harry Porter: The order of Phoenix
		<Author>J.K Rowling</Author>
		<ISBN>978-3-16-148410-0</ISBN>
		<Price>18.5</Price>
	</Book>
	
	<Book Category="Programming">
            XML in a Nutshell, Third Edition
		<Author>W. Scott Means</Author>
		<ISBN>978-0-59-600764-5</ISBN>
		<Price>31.8</Price>
	</Book>
	
	<Book Category="Science">A Brief History of Time
		<Author>Stephen Hawking</Author>
		<ISBN>978-0-55-338016-3</ISBN>
                <Price>16.25</Price>
	</Book>
</Books>
