=== DonOzOn/FPT-University-Excercise/HTML5Application/public_html/example/Book.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> 
    <element name="Books">
        <complexType>
            <sequence>
                <element name="Book" minOccurs="0" maxOccurs="unbounded">
                    <complexType mixed="true">
                        <sequence>
                            <element name="Name" minOccurs="1" maxOccurs="1">
                                <complexType mixed="true">
                                    <attribute name="language" type="string" use="optional"/>
                                </complexType>
                            </element>
                            <element name="Author" type="string" minOccurs="1" maxOccurs="1"/>
                            <element name="ISBN" type="string" minOccurs="1" maxOccurs="1"/>
                            <element name="Price" minOccurs="1" maxOccurs="1">
                                <simpleType>
                                    <restriction base="double">
                                        <minInclusive value="0"></minInclusive>
                                        <maxExclusive value="1000"></maxExclusive>
                                    </restriction>
                                </simpleType>
                            </element>
                        </sequence>
                        <attribute name="Category" type="string" use="required"/>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== DonOzOn/FPT-University-Excercise/HTML5Application/public_html/example/Book.xml
<?xml version="1.0"?>

<Books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="Book.xsd" >
	
	<Book Category="novel"> Harry Potter and the philosopher stone
		<Name>Harry Potter and the philosopher stone</Name>
		<Author>J.K Rowling</Author>
		<ISBN>978-3-16-148410-0</ISBN>
		<Price>18.5</Price>
	</Book>
	
	<Book Category="Programming">
		<Name>XML in a Nutshell, Third Edition</Name>
		<Author>W. Scott Means</Author>
		<ISBN>978-0-59-600764-5</ISBN>
		<Price>31.8</Price>
	</Book>
	
	<Book Category="Science">
		<Name>A Brief History of Time</Name>
		<Author>Stephen Hawking</Author>
		<ISBN>978-0-55-338016-3</ISBN>
		<Price>16.25</Price>
	</Book>
	
	
</Books>
