=== DonOzOn/FPT-University-Excercise/Topic 4/public_html/Atom.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/Atom.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE Atom SYSTEM "Atom.dtd">

    <Atom>
    ...
    </Atom>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Atom (Atoms)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Atoms (Status|Name|Symbol|AtomicNumber|AtomicWeight|BoilingPoint
 | unit|MeltingPoint| unit2|Density| unit3)*>
<!ATTLIST Atoms
    id CDATA #IMPLIED
    category CDATA #IMPLIED
  >
<!ATTLIST Atoms id ID #REQUIRED> 
<!ATTLIST Atoms category  (Solid|Gas|Liquid) #REQUIRED>
<!ATTLIST unit  flag  (K|C|F) #REQUIRED>
<!ATTLIST unit2 flag  (K|C|F) #REQUIRED>
<!ATTLIST unit3 flag  (grcm3 | kgm3) #REQUIRED>
<!--- Put your DTDDoc comment here. -->
<!ELEMENT Status (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Name (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Symbol (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT AtomicNumber (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT AtomicWeight (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT BoilingPoint (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT MeltingPoint (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Density (#PCDATA)>
<!ELEMENT unit (#PCDATA)>
<!ELEMENT unit2 (#PCDATA)>
<!ELEMENT unit3 (#PCDATA)>

=== DonOzOn/FPT-University-Excercise/Topic 4/public_html/Atom.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE Atom SYSTEM "Atom.dtd">
<Atom>
    <Atoms id = "AT1" category = "Gas">
        <Status>Gas</Status>
        <Name>Oxygen</Name>
        <Symbol>Oxygen = O</Symbol>
        <AtomicNumber>O = 2</AtomicNumber>
        <AtomicWeight>O = 15,9994</AtomicWeight>
        <BoilingPoint>O = 90,20</BoilingPoint>
        <unit flag = "K" > K</unit>
        <MeltingPoint>O = 6,82</MeltingPoint>
        <unit2 flag = "K">K</unit2>
        <Density>O = 1,429</Density>
        <unit3 flag = "grcm3">grcm3</unit3>
    </Atoms>
    <Atoms id = "AT2" category = "Gas">
        <Status>Gas</Status>
        <Name>Nitro</Name>
        <Symbol>Nitro = N</Symbol>
        <AtomicNumber>N = 2</AtomicNumber>
        <AtomicWeight>N = 14,0067</AtomicWeight>
        <BoilingPoint>N = 77,36</BoilingPoint>
        <unit flag = "K" >K</unit>
        <MeltingPoint>N = 5,56</MeltingPoint>
        <unit2 flag = "K">K</unit2>
        <Density>N = 1,251</Density>
        <unit3 flag = "grcm3">grcm3</unit3>
    </Atoms  >
    <Atoms id = "AT3" category = "Gas">
        <Status>Gas</Status>
        <Name>Hydrogen</Name>
        <Symbol>Hydrogen = H</Symbol>
        <AtomicNumber>H = 1</AtomicNumber>
        <AtomicWeight>H = 1.00794</AtomicWeight>
        <BoilingPoint>H = 20.28</BoilingPoint>
        <unit flag = "K" >K</unit>
        <MeltingPoint>H = 13.81</MeltingPoint>
        <unit2 flag = "K">K</unit2>
        <Density>H = 0.0899</Density>
        <unit3 flag = "grcm3">grcm3</unit3>
    </Atoms>
</Atom>
