=== DonOzOn/FPT-University-Excercise/Topic 4/public_html/ex2.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/ex2.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE bank SYSTEM "ex2.dtd">

    <bank>
    ...
    </bank>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT bank (banks)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT banks (account|customer|depositor)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT account EMPTY>
<!ATTLIST account
    account-number CDATA #IMPLIED
    branch-name CDATA #IMPLIED
    balance CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT customer EMPTY>
<!ATTLIST customer
    customer-name CDATA #IMPLIED
    customer-street CDATA #IMPLIED
    customer-city CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT depositor EMPTY>
<!ATTLIST depositor
    account-number CDATA #IMPLIED
    customer-name CDATA #IMPLIED
  >

=== DonOzOn/FPT-University-Excercise/Topic 4/public_html/ex2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE bank SYSTEM "ex2.dtd">
<bank>
    <banks>
        <account account-number="A-101" branch-name="Downtown" balance="500"></account>
        <customer customer-name="Johnson" customer-street="Alma" customer-city="Palo Alto"></customer>
        <depositor account-number="A-101" customer-name="Johnson"></depositor>
    </banks>
    <banks>
        <account account-number="A-102" branch-name="Perryridge" balance="400"></account>
        <customer customer-name="Johnson" customer-street="Alma" customer-city="Palo Alto"></customer>
        <depositor account-number="A-201" customer-name="Johnson"></depositor>
    </banks>
    <banks>
        <account account-number="A-201" branch-name="Brighton" balance="900"></account>
        <customer customer-name="Hayes" customer-street="Main" customer-city="Harrison"></customer>
        <depositor account-number="A-102" customer-name="Hayes"></depositor>
    </banks>

</bank>
